apiVersion: swacd.swacd.io/v1alpha1
kind: EdgeRoute
metadata:
  name: acme-route
  namespace: default
spec:
  fqdn: "acme.edge.cloudcfg.io"
  backendRefs:
    - name: acme-origin
  cache:
    enabled: true