apiVersion: swacd.swacd.io/v1alpha1
kind: OriginService
metadata:
  name: acme-origin
spec:
  endpoint: "https://acme-origin.example.com"
  healthCheck:
    path: "/healthz"
  auth:
    tls:
      enabled: true