apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6443
      protocol: TCP
  selector:
    app: {{ include "kcp.name" . }}
