apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1alpha1.tenants.swacd.swacd.io
spec:
  group: swacd.swacd.io
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            contactEmail:
              type: string
            displayName:
              type: string
            edgeServiceProviders:
              type: array
              items:
                type: object
            environment:
              type: string
            lob:
              type: string
        status:
          type: object
          properties:
            phase:
              type: string
            conditions:
              type: array
              items:
                type: object